# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'third-party/grantlee' : '@stable'
    'frameworks/kcalendarcore' : '@latest'
    'pim/kidentitymanagement' : '@same'
    'frameworks/breeze-icons': '@stable'
