# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'third-party/grantlee' : '@stable'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/kidentitymanagement' : '@latest'
