# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'pim/kidentitymanagement': '@same'
    'frameworks/breeze-icons': '@latest-kf6'
    'frameworks/ktexttemplate': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 allow-failing-tests-on: ['Windows']
 tests-run-in-parallel: True
 cmake-options: '-DWARNINGS_AS_ERRORS=ON'
 enable-lsan: True
