# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'frameworks/breeze-icons': '@latest-kf6'
    'libraries/ktexttemplate': '@stable'
